### PR TITLE
fixed issue in android version 4.4

### PR DESCRIPTION
**Pull request by San10694**
Prevent crashes on Android lower versions below lolypop.

### CODE REVIEW

**Comment by notmike101** [comment]
Will test this later tonight before merging.
If I don't get back to you within 24 hours, feel free to ping me.

**Comment by ManigandanRaamanathan** [comment]
@notmike101 pinging you

**Comment by gabrielbull** [comment]
@notmike101 Can you merge and publish? This issue makes android devices crash.

**Comment by notmike101** [comment]
Merged, closing.

**Comment by gabrielbull** [comment]
@notmike101 Thanks, can you publish an update (0.0.9?) on npm as well?

**Comment by thebylito** [comment]
Updated in npm too! Thanks.

**Pull request merged**
